### ISSUE TITLE
Problem when reloading a page

### ISSUE THREAD

**Issue by RoseratUgo** [A-C-Concepts/Froggy#4]
When reloading a page, the loading screen shifts to the left and a part of the site is visible on the right.

**Comment by RoseratUgo** [comment]
The problem has been solved by adding a user select none on the whole page.

```css
* {
    margin: 0;
    padding: 0;
    user-select: none;
}
```
