### ISSUE TITLE
Orbit controls bug

### ISSUE THREAD

**Issue by RoseratUgo** [A-C-Concepts/Froggy#5]
When you drag to move the 3D model and you pass on a div and you drop the orbits controls bug when you leave the div.
The orbits controls move all alone

**Comment by RoseratUgo** [comment]
The problem was fixed by putting a user select none on the whole page.
> _The problem came from the fact that the text was selected in drag on a div_

```css
* {
    margin: 0;
    padding: 0;
    user-select: none;
}
```
